### ISSUE TITLE
Layout mismatch to the design

### ISSUE THREAD

**Issue by Tonnamkit** [FameNu/IT30-Starter-Pack#15]
## BoardView.vue
![image](https://github.com/user-attachments/assets/e044d032-bc20-46e3-95f8-ebcd8db34f41)

## CommentView.vue
![image](https://github.com/user-attachments/assets/fd16e5cb-5a10-42c0-b912-6809a062bed5)

**Comment by LynchzDEV** [comment]
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcHBkeWRxY3Vpc3Uyc24wNTVrdzFqand0cjg5aXFocG5nZDBpbjBoayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/p3sprXNbsta8JlhWDg/giphy.gif)

**Comment by LynchzDEV** [comment]
@Tonnamkit how do i retrieve those data? or do i just add it manually?

**Comment by LynchzDEV** [comment]
@Tonnamkit FUCK IT WE BALL
