### ISSUE TITLE
typeOfLocation should has base value as 'regular' instead of null

### ISSUE THREAD

**Issue by ChinnaphatLoha** [FameNu/IT30-Starter-Pack#25]
# เดี๋ยว sponsor กดโกรธ

<img width="1440" alt="Screenshot 2567-07-23 at 1 06 00 AM" src="https://github.com/user-attachments/assets/59fee813-3ef8-481d-ac0a-56f3383be979">

**Comment by Tonnamkit** [comment]
เพิ่มให้แล้วครับ
