### ISSUE TITLE
Path "/none" and "/null" on each Calendar file

### ISSUE THREAD

**Issue by BomScoob12** [FameNu/IT30-Starter-Pack#26]
- ``/none`` is doesn't ref to Not-found component.
- ``/null`` is invalid url.

**Comment by LynchzDEV** [comment]
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcXpuZGk2dnVvcTN6OWt6ZjU4amMzNzU0emZvN3JqNmZ2ZzY0cGNxeCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/RkKQqizm4DWAXW9wwp/giphy.gif)
